### ISSUE TITLE
Request to add LP implementation for 2D 

### ISSUE THREAD

**Issue by trilanay** [jonarriza96/corrgen#2]
Thanks for the work. Could you please open source the LP implementation for the 2D map in the paper. 

I found [this](https://github.com/jonarriza96/corrgen/blob/IROS24/toy_example/figures/corridor_2d.py), but the `.pkl` dataset or the implementation is not in the repository.

**Comment by jonarriza96** [comment]
Hi,

Thank you for noticing this!

In the [latest commit](https://github.com/jonarriza96/corrgen/commit/5a0f48a0e02b4f0051df652e33ce21926171b701), I added a [script](https://github.com/jonarriza96/corrgen/blob/main/examples/corridor_2d.py) that replicates the 2D corridor implementation using a linear program (LP). While the implementation could still be optimized, it should serve as a solid starting point for prototyping.

Feel free to reach out if you encounter any issues!
